- create:
  - ~/.vim
  - ~/.vim/undo-history

- link:
    ~/.vimrc: editors/vim/vimrc
    ~/.config/nvim: editors/vim
    ~/.config/nvim/init.vim: editors/vim/vimrc

- shell:
  - [curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim, "Downloading vim plugin manager"]
  - [vim -c 'PlugInstall' -c 'qa!']
