- shell:
  - ["pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si && cd .. && rm -rf yay", Installing yay]

- yay:
  - tldr
  - vim
  - neovim
  - zsh
  - kitty
  - tmux
  - byobu
