- create:
  - ~/.oh-my-zsh/custom/plugins/

- clean:
  - ~/.zshrc.d

- shell:
  
  # - command: chsh -s $(which zsh)
  #   description: Making zsh the default shell
  #   stdin: true
  #   stdout: true
  - command: ${PWD}/scripts/set_zsh
    stdin: true
    stderr: true
  - [curl -L https://raw.githubusercontent.com/sbugzu/gruvbox-zsh/master/gruvbox.zsh-theme > ~/.oh-my-zsh/custom/themes/gruvbox.zsh-theme, Install gruvbox theme for OMZ]

- link:
    ~/.zshrc: 
      path: shells/zsh/zshrc
      force: true
    ~/.zshrc.d/:
      glob: true
      path: shells/zsh/zshrc.d/*
    ~/.util: util
