- shell:
  - command: ${PWD}/scripts/set_zsh
    stdin: true
    stderr: true
  - [curl -L https://raw.githubusercontent.com/sbugzu/gruvbox-zsh/master/gruvbox.zsh-theme > ~/.oh-my-zsh/custom/themes/gruvbox.zsh-theme, Install gruvbox theme for OMZ]

- link:
    ~/.zshrc: 
      path: shells/zsh/zshrc
      force: true
    ~/.util: util
