[".oh-my-zsh/custom/plugins/zshrc.d"]
    type = "git-repo"
    url = "https://github.com/zshzoo/zshrc.d"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/gruvbox.zsh-theme"]
    type = "file"
    url = "https://raw.githubusercontent.com/sbugzu/gruvbox-zsh/master/gruvbox.zsh-theme"
    refreshPeriod = "168h"
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
