.oh-my-zsh:
  type: archive
  url: 'https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz'
  exact: true
  stripComponents: 1
  refreshPeriod: 720h # 30 days

.omzcustom/plugins/zsh-vi-mode:
  type: archive
  url: 'https://github.com/jeffreytse/zsh-vi-mode/archive/master.tar.gz'
  exact: true
  stripComponents: 1
  refreshPeriod: 168h # 7 days
