[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zshrc.d"]
    type = "archive"
    url = "https://github.com/mattmc3/zshrc.d/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/gruvbox.zsh-theme"]
    type = "file"
    url = "https://raw.githubusercontent.com/nkzren/gruvbox-zsh/master/gruvbox.zsh-theme"
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger_devicons"]
    type = "git-repo"
    url = "https://github.com/alexanderjeurissen/ranger_devicons"
    refreshPeriod = "168h"
[".config/ranger/colorschemes"]
    type = "git-repo"
    url = "https://github.com/alfunx/ranger-colorschemes"
    refreshPeriod = "168h"
