- clean:
  - ~/.tmux

- create:
  - ~/.tmux/plugins

- shell:
  - [ rm -rf ~/.tmux/plugins/tpm ]
  - [ git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm ]
  - [ ~/.tmux/plugins/tpm/bin/install_plugins ]

- link:
    ~/.tmux.conf: shells/tmux/tmuxconfig
    ~/.byobu/.tmux.conf: shells/tmux/tmuxconfig
