- defaults:
    link:
      force: true

- shell:
  - [ranger --copy-config=all, "Generating ranger config files"] 
  - [rm -rf ~/.config/ranger/plugins/ranger_devicons]
  - [git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons, "Downloading devicons plugin"]

- link:
    ~/.config/ranger/commands.py: ranger/commands.py
    ~/.config/ranger/devicons.py: ranger/devicons.py
    ~/.config/ranger/rc.conf: ranger/rc.conf
    ~/.config/ranger/rifle.conf: ranger/rifle.conf
    
