#!/usr/bin/env sh
USER=$(whoami)

if [[ -d ~/.oh-my-zsh ]]; then
  echo "OMZ is already installed"
else
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

if (cat /etc/passwd | grep $USER | grep /usr/bin/zsh); then
  echo "ZSH is already the default shell"
else
  chsh -s /usr/bin/zsh
fi
