#!/usr/bin/env sh
USER=$(whoami)
ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}

if [[ -d ~/.oh-my-zsh ]]; then
  echo "OMZ is already installed"
else
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

if [[ -d $ZSH_CUSTOM/plugins/zshrc.d ]]; then
  echo "zshrc.d is already installed"
else
  sh -c "$(git clone https://github.com/zshzoo/zshrc.d $ZSH_CUSTOM/plugins/zshrc.d)"
fi

