icons_format = "{icon}"

[theme]
theme = "ctp-mocha"

[icons]
icons = "material-nf"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
format = "$variant"
interval = 1
[[block.click]]
button = "left"
cmd = "xkb-switch -n"

[[block]]
block = "music"
format = "$icon {$combo.str(max_w:20) $play $next |}"
player = "spotify"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
interval = 1

[[block]]
block = "memory"
format = "$icon $mem_total_used_percents.eng(w:2) "
format_alt = "$icon_swap $swap_used_percents.eng(w:2) "
interval = 1

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon home: $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon root: $available.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pwvucontrol"

[[block]]
block = "time"
interval = 1
format = "$icon  $timestamp.datetime(f:'%a %d/%m %H:%M:%S')"
